### ISSUE TITLE
Error Followed by previous issue

### ISSUE THREAD

**Issue by Sudershhh** [pranavraikote/CV-Brain-Tumor#2]
I corrected the last error and when i ran the code, it followed up with another error.

![Capture](https://user-images.githubusercontent.com/59435391/111843738-b6e31f80-8927-11eb-9c1f-d12b53d0e254.PNG)

  File "C:\Users\tgsud\Desktop\CV-Brain-Tumor-Feature-Extraction\Features.py", line 76, in image_process
    (x2,y2), (MA,ma), angle = cv2.fitEllipse(cnt)

error: OpenCV(4.0.1) C:\ci\opencv-suite_1573470242804\work\modules\imgproc\src\shapedescr.cpp:310: error: (-201:Incorrect size of input array) There should be at least 5 points to fit the ellipse in function 'cv::fitEllipse'

Could you please review your entire code once again and post the updatad code as soon as possible? It would really be helpful to me. Thanks in advance.

**Comment by pranavraikote** [comment]
This error is thrown whenever the contour is not that big enough to fit an ellipse. Simple solution is to put it under a try except block and discard that particular image. The code is updated.
